version: 2
project_name: griffin-commerce-demo

builds:
  - id: griffin
    main: ./main.go
    binary: griffin
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

archives:
  - id: griffin-archive
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
      - zip
    files:
      - none*  # This will only include the binary

dockers_v2:
  - images:
      - docker.flame.org/library/griffin-commerce-demo
    dockerfile: Dockerfile-goreleaser
    tags:
      - "v{{ .Version }}"
      - "{{ if .IsNightly }}nightly{{ end }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    labels:
      "org.opencontainers.image.description": "Demo apps for Cardinal's AI tools"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
    extra_files:
      - entrypoint.sh
      - services/images/static

checksum:
  name_template: 'checksums.txt'
