apiVersion: v1
kind: Namespace
metadata:
  name: adani-demo
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    purpose: adani-solar-telemetry-simulator
