apiVersion: v1
kind: Namespace
metadata:
  name: nvcf-demo
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    purpose: nvcf-telemetry-simulator
