apiVersion: v1
kind: Service
metadata:
  name: dbaas-faults
  labels:
    app: dbaas
    purpose: airtel-telemetry-simulator
spec:
  type: ClusterIP
  selector:
    app: dbaas
  ports:
    - name: faults
      port: 9999
      targetPort: faults
      protocol: TCP
